title: Kunvar Thaman
description: 1-page website that contains links to kunvar's profiles
baseurl: "https://firstuserhere.github.io"
url: https://firstuserhere.github.io

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Kunvar Thaman
  description:
    - Hello! I'm Kunvar.
    - I'm a machine learning engineer.
    - I take apart and analyze Neural networks.
    - Sometimes I put them back together in clever ways.
  interests:
    - Machine Learning
    - Mechanistic Interpretability
    - Reading books
    - running, biking, jumping rope, lifting, backpacking
    - Exploring hidden corners of the internet
    - Writing (fiction as well as non-fiction)
    - Listening to classical music
    - Geography and History (especially pre-history)
  contact:
    personal: 1stuserhere@gmail.com
    collaborations: kunvar@mechinterp.com
    work: kunvar@stdint.com
  profiles:
    website: https://kunvarthaman.com
    twitter: https://twitter.com/firstuserhere
    github: https://github.com/firstuserhere
    discord: firstuserhere
    goodreads: https://goodreads.com/firstuserhere 
    lesswrong: https://lesswrong.com/users/1stuserhere
    greaterwrong: https://greaterwrong.com/users/1stuserhere


exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
