title: Kunvar Thaman
description: 1-page website that contains links to kunvar's profiles
baseurl: "https://firstuserhere.github.io"
url: https://firstuserhere.github.io

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Kunvar Thaman
  description:
    - Hello! I'm Kunvar.
    - I'm a machine learning engineer.
    - I take apart and analyze Neural networks.
    - Sometimes I put them back together in clever ways.
  interests:
    - Training large scale neural networks of various forms
    - Mechanistic Interpretability research
    - Reading books (though this has gone down significantly over the years - check my Goodreads!)
    - Running, biking, climbing and hiking up mountains, lifting heavy weights (checkout my Strava!)
    - Exploring various cultures, cities (nightwalking is fun!), and dancing
    - Listening to classical music
    - Geography and History (especially pre-history)
  contact:
    personal: 1stuserhere@gmail.com
    collaborations: kunvar@mechinterp.com
  social-media:
    twitter: https://x.com/firstuserhere
    github: https://github.com/firstuserhere
    discord: https://discordapp.com/users/1060971001002872843
    strava: https://www.strava.com/athletes/111945782
    goodreads: https://goodreads.com/firstuserhere 
    lesswrong: https://lesswrong.com/users/1stuserhere 

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
