# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Kunvar Thaman
description: 1-page website that contains links to kunvar's profiles
baseurl: "https://firstuserhere.github.io"
url: https://firstuserhere.github.io

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Kunvar Thaman
  description:
    - Hello!
    - I'm also known as firstuserhere. 
    - Welcome to my website
  contact:
    email_primary: 1stuserhere@gmail.com
    email_secondary: firstuserhere@proton.me

  website: https://mechinterp.com
  profiles:
    twitter: https://twitter.com/firstuserhere
    github: https://github.com/firstuserhere

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
